services:
  # =============================================
  # AUTH SERVICE (Spring Boot + Java 17)
  # =============================================
  auth_service:
    build:
      context: ../backend/auth
      dockerfile: Dockerfile
    container_name: auth_service
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_CONTAINER}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8080:8080"
    networks:
      - proticket_net

  business_service:
    build:
      context: ../backend/business
      dockerfile: Dockerfile
    container_name: business_service
    restart: always
    ports:
      - "8001:8000"
    env_file:
      - ../backend/business/.env
    volumes:
      - ../backend/business:/app
    depends_on:
      - postgres_business
    networks:
      - proticket_net

networks:
  proticket_net:
    external: true