services:
  frontend_service:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: frontend_service
    restart: always
    ports:
      - "5173:80"   # host:container (http://localhost:5173)
    networks:
      - proticket_net

networks:
  proticket_net:
    external: true
    name: ${NETWORK_NAME}
